### ISSUE TITLE
Cannot route multiple keys to same queue

### ISSUE THREAD

**Issue by ScottFreeCode** [shanejansen/touchstone#24]
I have an app that has a queue "all" on which it receives from multiple routing keys, "route.a", "route.b", "route.c". (This helps with ordering of different messages that affect the same object, when the app comes back up after downtime. Arguably the root problem is the app's structure but it's a legacy app we're hoping to first get Touchstone tests for then use those tests when refactoring or replacing. Then again: Rabbit plainly allows different sources to use their own routing keys and one recipient to route them into the same queue.) This gives me Touchstone failures, 'This exchange "my.exchange", routing-key "route.b" combination is not defined. Check your "rabbit.yml" defaults.' (and same for route.c) even though I have this in my.exchange:

```yml
- name: all
  routingKey: route.a
- name: all
  routingKey: route.b
- name: all
  routingKey: route.c
```
